---
- hosts: all
  roles:
    - roles/pup
    - roles/spatialite
    - { role: geerlingguy.pip, become: yes }
    - andrewrothstein.jq

  vars:
    pip_install_packages:
      - name: shapefile-to-sqlite
  tasks:
    - ansible.builtin.include_tasks: tasks/timezones.yml
    # - ansible.builtin.include_tasks: tasks/bouys_history.yml
