#!/usr/bin/env node

const fs = require('fs');
const index_bouy_history = require('../fixture/index_bouy_history');
const passed = {};
const args_handler = { bouys: true }
for (let i = 2; i < process.argv.length; ++i) {
    if (args_handler[process.argv[i]]) {
        passed[process.argv[i]] = process.argv[i + 1];
        ++i;
    }
}

const bouys_to_process = (passed.bouys && passed.bouys.split(',')) || fs.readdirSync('bouy_metadata');
function serial_promises() {
    let prom = Promise.resolve();
    bouys_to_process.forEach(p => {
      prom = prom.then(() => index_bouy_history(p))
    })
    return prom;
}
function main () {
    serial_promises().then(() => process.exit(0));
}

main();

